"""add indicators and strategy_indicators tables

Revision ID: 310e3b3a320c
Revises: f659278ada58
Create Date: 2026-01-21 23:40:39.217790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310e3b3a320c'
down_revision: Union[str, None] = 'f659278ada58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.drop_index('idx_accounts_autotrade_demo')
        batch_op.drop_index('idx_accounts_autotrade_real')
        batch_op.drop_index('idx_accounts_is_active')
        batch_op.drop_index('idx_accounts_user_id')
        batch_op.create_index(batch_op.f('ix_accounts_autotrade_demo'), ['autotrade_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_autotrade_real'), ['autotrade_real'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('autotrade_configs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('account_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('strategy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(1.0)'))
        batch_op.alter_column('min_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.7)'))
        batch_op.alter_column('soros_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('martingale_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_timeframe'), ['timeframe'], unique=False)

    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('rsi', 'macd', 'bollinger', 'trend_following', 'mean_reversion', 'multi_oscillator', 'scalping', 'breakout', 'confluence', 'confluence_long_term', 'custom', name='strategytype'),
               existing_nullable=False)
        batch_op.alter_column('total_profit',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_loss',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.drop_index('idx_strategies_account_id')
        batch_op.drop_index('idx_strategies_is_active')
        batch_op.drop_index('idx_strategies_user_id')

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('idx_trades_account_id')
        batch_op.drop_index('idx_trades_closed_at')
        batch_op.drop_index('idx_trades_placed_at')
        batch_op.drop_index('idx_trades_status')
        batch_op.drop_index('idx_trades_strategy_id')
        batch_op.create_index(batch_op.f('ix_trades_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_strategy_id'), ['strategy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_trades_status'))
        batch_op.create_index('idx_trades_strategy_id', ['strategy_id'], unique=False)
        batch_op.create_index('idx_trades_status', ['status'], unique=False)
        batch_op.create_index('idx_trades_placed_at', ['placed_at'], unique=False)
        batch_op.create_index('idx_trades_closed_at', ['closed_at'], unique=False)
        batch_op.create_index('idx_trades_account_id', ['account_id'], unique=False)

    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index('idx_strategies_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_strategies_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_strategies_account_id', ['account_id'], unique=False)
        batch_op.alter_column('total_loss',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_profit',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('type',
               existing_type=sa.Enum('rsi', 'macd', 'bollinger', 'trend_following', 'mean_reversion', 'multi_oscillator', 'scalping', 'breakout', 'confluence', 'confluence_long_term', 'custom', name='strategytype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_timeframe'))

    with op.batch_alter_table('autotrade_configs', schema=None) as batch_op:
        batch_op.alter_column('martingale_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('soros_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('min_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.7)'))
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(1.0)'))
        batch_op.alter_column('strategy_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('account_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_is_active'))
        batch_op.drop_index(batch_op.f('ix_accounts_autotrade_real'))
        batch_op.drop_index(batch_op.f('ix_accounts_autotrade_demo'))
        batch_op.create_index('idx_accounts_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_accounts_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_accounts_autotrade_real', ['autotrade_real'], unique=False)
        batch_op.create_index('idx_accounts_autotrade_demo', ['autotrade_demo'], unique=False)
        batch_op.alter_column('currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
