"""add maintenance_logout_at to users

Revision ID: add_maintenance_logout_at
Revises: 
Create Date: 2026-02-01 07:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_maintenance_logout_at'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('users', sa.Column('maintenance_logout_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('users', 'maintenance_logout_at')
    # ### end Alembic commands ###
