"""Add indexes to Trade table for performance

Revision ID: f659278ada58
Revises: c883b7582031
Create Date: 2026-01-17 14:18:17.775399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f659278ada58'
down_revision: Union[str, None] = 'c883b7582031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add index on placed_at for ordering queries
    op.create_index('ix_trades_placed_at', 'trades', ['placed_at'])
    
    # Add index on expires_at for monitoring active trades
    op.create_index('ix_trades_expires_at', 'trades', ['expires_at'])
    
    # Add index on closed_at for filtering closed trades
    op.create_index('ix_trades_closed_at', 'trades', ['closed_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_closed_at', table_name='trades')
    op.drop_index('ix_trades_expires_at', table_name='trades')
    op.drop_index('ix_trades_placed_at', table_name='trades')
    # ### end Alembic commands ###
