"""Signals router"""
from fastapi import APIRouter, Depends, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func
from typing import List, Optional
from datetime import datetime, timezone
from loguru import logger

from core.database import get_db
from core.security import get_current_active_user
from models import User, Signal, Strategy, Asset
from schemas import SignalsListResponse, SignalResponse

router = APIRouter()


@router.get("", response_model=SignalsListResponse)
async def get_signals(
    strategy_id: str = None,
    asset_id: int = None,
    executed: bool = None,
    limit: int = Query(50, le=100),  
    cursor: Optional[str] = Query(None, description="Cursor ISO UTC para paginação (ex: 2024-01-15T10:30:00+00:00)"),
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Get signals generated by user's strategies with cursor-based pagination
    
    **Cursor deve ser UTC** - use datetime.utcnow().isoformat()
    """
    query = select(Signal).join(Strategy).where(Strategy.user_id == current_user.id)

    if strategy_id:
        query = query.where(Signal.strategy_id == strategy_id)

    if asset_id:
        query = query.where(Signal.asset_id == asset_id)

    if executed is not None:
        query = query.where(Signal.is_executed == executed)
    
    # CURSOR-BASED PAGINATION: Mais eficiente que OFFSET para grandes volumes
    if cursor:
        try:
            cursor_dt = datetime.fromisoformat(cursor).replace(tzinfo=timezone.utc)
            query = query.where(Signal.created_at < cursor_dt)
        except ValueError:
            logger.warning(f"[SIGNALS] Cursor inválido (esperado ISO UTC): {cursor}")
    
    # Contagem total (otimizada: só na primeira página)
    total = None
    if not cursor:
        count_result = await db.execute(
            select(func.count()).select_from(query)
        )
        total = count_result.scalar()

    query = query.order_by(Signal.created_at.desc()).limit(limit)
    result = await db.execute(query)
    signals = result.scalars().all()

    # Buscar nomes de estratégias e ativos
    strategy_ids = list(set([s.strategy_id for s in signals]))
    asset_ids = list(set([s.asset_id for s in signals]))

    strategies = {}
    assets = {}

    if strategy_ids:
        strategies_result = await db.execute(
            select(Strategy.id, Strategy.name).where(Strategy.id.in_(strategy_ids))
        )
        strategies = {row[0]: {'name': row[1]} for row in strategies_result}

    if asset_ids:
        assets_result = await db.execute(
            select(Asset.id, Asset.name, Asset.symbol).where(Asset.id.in_(asset_ids))
        )
        assets = {row[0]: {'name': row[1], 'symbol': row[2]} for row in assets_result}

    signals_response = []
    next_cursor = None
    
    for i, signal in enumerate(signals):
        indicators_val = signal.indicators if signal.indicators else []
        
        signals_response.append(
            SignalResponse(
                id=signal.id,
                strategy_id=signal.strategy_id,
                strategy_name=strategies.get(signal.strategy_id, {}).get('name') if signal.strategy_id in strategies else None,
                asset_id=str(signal.asset_id),
                asset_name=assets.get(signal.asset_id, {}).get('name'),
                symbol=assets.get(signal.asset_id, {}).get('symbol', ''),
                signal_type=signal.signal_type.value if hasattr(signal.signal_type, 'value') else str(signal.signal_type),
                confidence=signal.confidence,
                timeframe=signal.timeframe,
                price=signal.price,
                indicators=indicators_val,
                confluence=signal.confluence,
                is_executed=signal.is_executed,
                created_at=signal.created_at
            )
        )
        
        # Último item vira o próximo cursor
        if i == len(signals) - 1 and len(signals) == limit:
            next_cursor = signal.created_at.isoformat()

    return SignalsListResponse(
        signals=signals_response,
        total=total,
        page=1,
        page_size=limit,
        next_cursor=next_cursor  # Frontend usa para carregar mais
    )
